#!/bin/sh

# # Use neovim for vim if present.
# [ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
# for command in mount umount sv pacman updatedb su ; do
# 	alias $command="sudo $command"
# done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -h --color=auto" \
	grep="grep --color=auto" \
	diff="diff" \
	# ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	pow="doas /sbin/poweroff" \
        re="doas /sbin/reboot" \
        zzz="doas doas /usr/sbin/acpiconf -s 3"
	e="$EDITOR" \
	p="doas pkg" \
	pi="doas pkg install" \
	pr="doas pkg remove" \
	z="zathura"
        
# alias \
	# magit="nvim -c MagitOnly" \
	# ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	# weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \

        alias \
            pdfcompress="gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -sOutputFile=compressed.pdf $1" \
            sm18="env WINEPREFIX=/home/i/.local/share/wineprefixes/sm18/ wine ~/.local/share/wineprefixes/sm18/drive_c/SuperMemo/sm18.exe"
